export const products = [
  {
    id: 1,
    name: "Slimvera (250ml)",
    price: 59.49,
    oldPrice: 85.49,
    image: "/images/product-1.png",
    category: "Weight Loss",
    description: "Advanced weight loss supplement with natural ingredients",
  },
  {
    id: 2,
    name: "Slimvera (320ml)",
    price: 102.99,
    oldPrice: null,
    image: "/images/product-1.png",
    category: "Weight Loss",
    description: "Premium weight loss formula in larger size",
  },
  {
    id: 3,
    name: "EnergyBoost Pro",
    price: 45.99,
    oldPrice: 65.99,
    image: "/images/product-1.png",
    category: "Energy",
    description: "Natural energy booster for daily vitality",
  },
  {
    id: 4,
    name: "VitaCore Plus",
    price: 78.5,
    oldPrice: null,
    image: "/images/product-1.png",
    category: "Vitamins",
    description: "Complete multivitamin complex for overall health",
  },
  {
    id: 5,
    name: "OmegaHealth Gold",
    price: 89.99,
    oldPrice: 120.0,
    image: "/images/product-1.png",
    category: "Omega-3",
    description: "Premium omega-3 supplement for heart health",
  },
  {
    id: 6,
    name: "Collagen Beauty",
    price: 67.25,
    oldPrice: null,
    image: "/images/product-1.png",
    category: "Beauty",
    description: "Collagen supplement for skin and hair health",
  },
  {
    id: 7,
    name: "Probiotic Balance",
    price: 52.75,
    oldPrice: 75.5,
    image: "/images/product-1.png",
    category: "Digestive Health",
    description: "Advanced probiotic formula for gut health",
  },
  {
    id: 8,
    name: "SleepWell Natural",
    price: 38.99,
    oldPrice: null,
    image: "/images/product-1.png",
    category: "Sleep",
    description: "Natural sleep aid with calming herbs",
  },
  {
    id: 9,
    name: "JointFlex Support",
    price: 95.0,
    oldPrice: 125.0,
    image: "/images/product-1.png",
    category: "Joint Health",
    description: "Comprehensive joint support supplement",
  },
  {
    id: 10,
    name: "BrainFocus Elite",
    price: 112.5,
    oldPrice: null,
    image: "/images/product-1.png",
    category: "Cognitive",
    description: "Advanced cognitive enhancement formula",
  },
  {
    id: 11,
    name: "ImmuneDefense Max",
    price: 73.25,
    oldPrice: 95.0,
    image: "/images/product-1.png",
    category: "Immunity",
    description: "Maximum strength immune system support",
  },
  {
    id: 12,
    name: "HeartHealth Complete",
    price: 88.75,
    oldPrice: null,
    image: "/images/product-1.png",
    category: "Heart Health",
    description: "Complete cardiovascular health support",
  },
  {
    id: 13,
    name: "BoneStrength Plus",
    price: 56.99,
    oldPrice: 78.5,
    image: "/images/product-1.png",
    category: "Bone Health",
    description: "Advanced bone health and calcium supplement",
  },
  {
    id: 14,
    name: "VisionCare Pro",
    price: 82.0,
    oldPrice: null,
    image: "/images/product-1.png",
    category: "Eye Health",
    description: "Professional eye health and vision support",
  },
  {
    id: 15,
    name: "LiverDetox Cleanse",
    price: 69.99,
    oldPrice: 89.99,
    image: "/images/product-1.png",
    category: "Detox",
    description: "Natural liver detoxification and cleansing",
  },
  {
    id: 16,
    name: "SkinGlow Essential",
    price: 47.5,
    oldPrice: null,
    image: "/images/product-1.png",
    category: "Beauty",
    description: "Essential nutrients for radiant skin",
  },
  {
    id: 17,
    name: "MoodBalance Natural",
    price: 61.25,
    oldPrice: 79.99,
    image: "/images/product-1.png",
    category: "Mental Health",
    description: "Natural mood balancing and stress relief",
  },
  {
    id: 18,
    name: "FitnessFuel Elite",
    price: 104.99,
    oldPrice: null,
    image: "/images/product-1.png",
    category: "Sports Nutrition",
    description: "Elite sports nutrition and performance fuel",
  },
  {
    id: 19,
    name: "AntiAging Complex",
    price: 118.75,
    oldPrice: 145.0,
    image: "/images/product-1.png",
    category: "Anti-Aging",
    description: "Advanced anti-aging and longevity formula",
  },
  {
    id: 20,
    name: "DigestiveEase Plus",
    price: 43.99,
    oldPrice: null,
    image: "/images/product-1.png",
    category: "Digestive Health",
    description: "Enhanced digestive comfort and support",
  },
  {
    id: 21,
    name: "HormoneBalance Pro",
    price: 97.5,
    oldPrice: 125.0,
    image: "/images/product-1.png",
    category: "Hormonal Health",
    description: "Professional hormonal balance support",
  },
  {
    id: 22,
    name: "MetabolismBoost",
    price: 71.25,
    oldPrice: null,
    image: "/images/product-1.png",
    category: "Metabolism",
    description: "Natural metabolism boosting supplement",
  },
  {
    id: 23,
    name: "StressRelief Natural",
    price: 54.99,
    oldPrice: 72.5,
    image: "/images/product-1.png",
    category: "Stress Relief",
    description: "Natural stress relief and relaxation aid",
  },
  {
    id: 24,
    name: "MemoryEnhance Max",
    price: 108.75,
    oldPrice: null,
    image: "/images/product-1.png",
    category: "Cognitive",
    description: "Maximum memory enhancement and brain support",
  },
  {
    id: 25,
    name: "DetoxComplete Cleanse",
    price: 76.5,
    oldPrice: 98.99,
    image: "/images/product-1.png",
    category: "Detox",
    description: "Complete body detoxification and cleansing",
  },
  {
    id: 26,
    name: "BeautyGlow Premium",
    price: 134.99,
    oldPrice: null,
    image: "/images/product-1.png",
    category: "Beauty",
    description: "Premium beauty and anti-aging formula",
  },
  {
    id: 27,
    name: "WellnessCore Complete",
    price: 89.75,
    oldPrice: 115.0,
    image: "/images/product-1.png",
    category: "Overall Wellness",
    description: "Complete wellness and vitality support",
  },
  {
    id: 28,
    name: "PerformancePeak Elite",
    price: 156.25,
    oldPrice: null,
    image: "/images/product-1.png",
    category: "Performance",
    description: "Elite performance and peak physical condition",
  },
  {
    id: 29,
    name: "HealthGuard Plus",
    price: 92.99,
    oldPrice: 118.5,
    image: "/images/product-1.png",
    category: "Immunity",
    description: "Plus immunity and health protection",
  },
];
