export const products = [
  {
    id: 1,
    name: "Slimvera (250ml)",
    price: 59.49,
    oldPrice: 85.49,
    image: "/images/product-1.png",
    category: "Weight Loss",
    description: "Advanced weight loss supplement with natural ingredients",
    longDescription:
      "Cras id semper elit. Donec egestas ac justo eget porta. Integer ac egestas nulla. Mauris tristique tincidunt mi eu imperdiet. Nullam vitae rutrum est. Integer ac odio id mi tincidunt mollis ut vitae neque. Suspendisse leo nunc, facilisis nec lorem eget, molestie bibendum dui. Morbi ornare sapien at ex pharetra, eget porta ipsum faucibus.",
    ingredients: [
      { name: "Garcinia Cambogia extract powder 60% HCA", amount: "100 mg" },
      { name: "Caffeine Anhydrous", amount: "100 mg" },
      { name: "Guarana extract (20% caffeine)", amount: "10 mg" },
      { name: "Vitamin B6 (pyridoxine HCl)", amount: "20 mg" },
      { name: "Vitamin B2 (riboflavin)", amount: "0.6 mg" },
      { name: "Chromium (as chromium picolinate)", amount: "0.1 mg" },
      { name: "Sillicium dioxide", amount: "4 mg" },
      { name: "Magnesium stearaat", amount: "4 mg" },
    ],
    images: [
      "/images/product-1.png",
      "/images/product-1.png",
      "/images/product-1.png",
      "/images/product-1.png",
      "/images/product-1.png",
      "/images/product-1.png",
    ],
  },
  {
    id: 2,
    name: "Slimvera (320ml)",
    price: 102.99,
    oldPrice: null,
    image: "/images/product-1.png",
    category: "Weight Loss",
    description: "Premium weight loss formula in larger size",
    longDescription:
      "Premium weight loss supplement in a larger 320ml size. Advanced formula with natural ingredients designed for maximum effectiveness and convenience.",
    ingredients: [
      { name: "Garcinia Cambogia extract powder 60% HCA", amount: "120 mg" },
      { name: "Caffeine Anhydrous", amount: "120 mg" },
      { name: "Guarana extract (20% caffeine)", amount: "15 mg" },
      { name: "Vitamin B6 (pyridoxine HCl)", amount: "25 mg" },
      { name: "Vitamin B2 (riboflavin)", amount: "0.8 mg" },
      { name: "Chromium (as chromium picolinate)", amount: "0.15 mg" },
      { name: "Sillicium dioxide", amount: "5 mg" },
      { name: "Magnesium stearaat", amount: "5 mg" },
    ],
    images: [
      "/images/product-1.png",
      "/images/product-1.png",
      "/images/product-1.png",
      "/images/product-1.png",
      "/images/product-1.png",
      "/images/product-1.png",
    ],
  },
  {
    id: 3,
    name: "EnergyBoost Pro",
    price: 45.99,
    oldPrice: 65.99,
    image: "/images/product-1.png",
    category: "Energy",
    description: "Natural energy booster for daily vitality",
    longDescription:
      "Premium natural energy supplement designed to boost daily vitality and mental alertness. Formulated with scientifically-proven ingredients for sustained energy without crashes.",
    ingredients: [
      { name: "Caffeine Anhydrous", amount: "150 mg" },
      { name: "L-Theanine", amount: "200 mg" },
      { name: "B-Vitamin Complex", amount: "100 mg" },
      { name: "Ginseng Extract", amount: "50 mg" },
      { name: "Guarana Seed Extract", amount: "25 mg" },
      { name: "Taurine", amount: "500 mg" },
      { name: "Creatine Monohydrate", amount: "3 g" },
      { name: "Magnesium Citrate", amount: "100 mg" },
    ],
    images: [
      "/images/product-1.png",
      "/images/product-1.png",
      "/images/product-1.png",
      "/images/product-1.png",
      "/images/product-1.png",
      "/images/product-1.png",
    ],
  },
  {
    id: 4,
    name: "VitaCore Plus",
    price: 78.5,
    oldPrice: null,
    image: "/images/product-1.png",
    category: "Vitamins",
    description: "Complete multivitamin complex for overall health",
    longDescription:
      "Comprehensive multivitamin complex formulated to support overall health and wellness. Contains essential vitamins and minerals in optimal ratios for maximum absorption and effectiveness.",
    ingredients: [
      { name: "Vitamin A (as Retinyl Palmitate)", amount: "5000 IU" },
      { name: "Vitamin C (as Ascorbic Acid)", amount: "1000 mg" },
      { name: "Vitamin D3 (Cholecalciferol)", amount: "2000 IU" },
      { name: "Vitamin E (as d-alpha Tocopherol)", amount: "400 IU" },
      { name: "Vitamin K2 (as MK-7)", amount: "100 mcg" },
      { name: "B-Complex Vitamins", amount: "Various" },
      { name: "Calcium (as Calcium Carbonate)", amount: "500 mg" },
      { name: "Iron (as Ferrous Fumarate)", amount: "18 mg" },
    ],
    images: [
      "/images/product-1.png",
      "/images/product-1.png",
      "/images/product-1.png",
      "/images/product-1.png",
      "/images/product-1.png",
      "/images/product-1.png",
    ],
  },
  {
    id: 5,
    name: "OmegaHealth Gold",
    price: 89.99,
    oldPrice: 120.0,
    image: "/images/product-1.png",
    category: "Omega-3",
    description: "Premium omega-3 supplement for heart health",
    longDescription:
      "High-quality omega-3 fatty acid supplement sourced from wild-caught fish. Formulated to support cardiovascular health, brain function, and overall wellness with optimal EPA and DHA ratios.",
    ingredients: [
      { name: "Fish Oil (from Wild Alaskan Salmon)", amount: "2000 mg" },
      { name: "EPA (Eicosapentaenoic Acid)", amount: "800 mg" },
      { name: "DHA (Docosahexaenoic Acid)", amount: "600 mg" },
      { name: "DPA (Docosapentaenoic Acid)", amount: "100 mg" },
      { name: "Vitamin E (as Natural d-alpha Tocopherol)", amount: "20 IU" },
      { name: "Astaxanthin", amount: "2 mg" },
      { name: "Lemon Oil", amount: "5 mg" },
      { name: "Rosemary Extract", amount: "10 mg" },
    ],
    images: [
      "/images/product-1.png",
      "/images/product-1.png",
      "/images/product-1.png",
      "/images/product-1.png",
      "/images/product-1.png",
      "/images/product-1.png",
    ],
  },
  {
    id: 6,
    name: "Collagen Beauty",
    price: 67.25,
    oldPrice: null,
    image: "/images/product-1.png",
    category: "Beauty",
    description: "Collagen supplement for skin and hair health",
    longDescription:
      "Premium collagen peptide supplement specifically formulated to support skin elasticity, hair strength, and nail health. Hydrolyzed for maximum absorption and effectiveness.",
    ingredients: [
      { name: "Hydrolyzed Collagen Peptides (Type I & III)", amount: "10 g" },
      { name: "Biotin", amount: "5000 mcg" },
      { name: "Vitamin C (as Ascorbic Acid)", amount: "500 mg" },
      { name: "Hyaluronic Acid", amount: "100 mg" },
      { name: "Silica (from Bamboo Extract)", amount: "50 mg" },
      { name: "Zinc (as Zinc Picolinate)", amount: "15 mg" },
      { name: "Copper (as Copper Gluconate)", amount: "2 mg" },
      { name: "MSM (Methylsulfonylmethane)", amount: "500 mg" },
    ],
    images: [
      "/images/product-1.png",
      "/images/product-1.png",
      "/images/product-1.png",
      "/images/product-1.png",
      "/images/product-1.png",
      "/images/product-1.png",
    ],
  },
  {
    id: 7,
    name: "Probiotic Balance",
    price: 52.75,
    oldPrice: 75.5,
    image: "/images/product-1.png",
    category: "Digestive Health",
    description: "Advanced probiotic formula for gut health",
    longDescription:
      "Advanced probiotic supplement containing multiple strains of beneficial bacteria to support digestive health, immune function, and overall gut microbiome balance.",
    ingredients: [
      { name: "Lactobacillus Acidophilus", amount: "10 billion CFU" },
      { name: "Bifidobacterium Bifidum", amount: "5 billion CFU" },
      { name: "Lactobacillus Plantarum", amount: "5 billion CFU" },
      { name: "Bifidobacterium Longum", amount: "3 billion CFU" },
      { name: "Streptococcus Thermophilus", amount: "2 billion CFU" },
      { name: "Inulin (Prebiotic Fiber)", amount: "500 mg" },
      { name: "Fructooligosaccharides (FOS)", amount: "300 mg" },
      { name: "Vitamin D3", amount: "1000 IU" },
    ],
    images: [
      "/images/product-1.png",
      "/images/product-1.png",
      "/images/product-1.png",
      "/images/product-1.png",
      "/images/product-1.png",
      "/images/product-1.png",
    ],
  },
  {
    id: 8,
    name: "SleepWell Natural",
    price: 38.99,
    oldPrice: null,
    image: "/images/product-1.png",
    category: "Sleep",
    description: "Natural sleep aid with calming herbs",
    longDescription:
      "Natural sleep supplement formulated with calming herbs and amino acids to promote restful sleep, reduce stress, and improve sleep quality without dependency.",
    ingredients: [
      { name: "Melatonin", amount: "5 mg" },
      { name: "L-Theanine", amount: "200 mg" },
      { name: "Chamomile Extract", amount: "300 mg" },
      { name: "Valerian Root Extract", amount: "200 mg" },
      { name: "Passionflower Extract", amount: "150 mg" },
      { name: "Lemon Balm Extract", amount: "100 mg" },
      { name: "Magnesium (as Magnesium Glycinate)", amount: "200 mg" },
      { name: "5-HTP (5-Hydroxytryptophan)", amount: "100 mg" },
    ],
    images: [
      "/images/product-1.png",
      "/images/product-1.png",
      "/images/product-1.png",
      "/images/product-1.png",
      "/images/product-1.png",
      "/images/product-1.png",
    ],
  },
  {
    id: 9,
    name: "JointFlex Support",
    price: 95.0,
    oldPrice: 125.0,
    image: "/images/product-1.png",
    category: "Joint Health",
    description: "Comprehensive joint support supplement",
    longDescription:
      "Advanced joint health supplement designed to support joint flexibility, reduce inflammation, and promote cartilage health with clinically-proven ingredients.",
    ingredients: [
      { name: "Glucosamine Sulfate", amount: "1500 mg" },
      { name: "Chondroitin Sulfate", amount: "1200 mg" },
      { name: "MSM (Methylsulfonylmethane)", amount: "1000 mg" },
      { name: "Hyaluronic Acid", amount: "100 mg" },
      { name: "Turmeric Extract (95% Curcuminoids)", amount: "500 mg" },
      { name: "Boswellia Serrata Extract", amount: "300 mg" },
      { name: "Omega-3 Fish Oil", amount: "1000 mg" },
      { name: "Vitamin D3", amount: "2000 IU" },
    ],
    images: [
      "/images/product-1.png",
      "/images/product-1.png",
      "/images/product-1.png",
      "/images/product-1.png",
      "/images/product-1.png",
      "/images/product-1.png",
    ],
  },
  {
    id: 10,
    name: "BrainFocus Elite",
    price: 112.5,
    oldPrice: null,
    image: "/images/product-1.png",
    category: "Cognitive",
    description: "Advanced cognitive enhancement formula",
    longDescription:
      "Premium cognitive enhancement supplement formulated to improve memory, focus, mental clarity, and overall brain function using scientifically-backed nootropic ingredients.",
    ingredients: [
      { name: "Bacopa Monnieri Extract (50% Bacosides)", amount: "300 mg" },
      { name: "Lion's Mane Mushroom Extract", amount: "500 mg" },
      { name: "Phosphatidylserine", amount: "100 mg" },
      { name: "Acetyl-L-Carnitine", amount: "500 mg" },
      { name: "Alpha-GPC (Alpha-Glycerylphosphorylcholine)", amount: "300 mg" },
      { name: "Vinpocetine", amount: "20 mg" },
      { name: "Huperzine A", amount: "100 mcg" },
      { name: "DHA (Docosahexaenoic Acid)", amount: "500 mg" },
    ],
    images: [
      "/images/product-1.png",
      "/images/product-1.png",
      "/images/product-1.png",
      "/images/product-1.png",
      "/images/product-1.png",
      "/images/product-1.png",
    ],
  },
  {
    id: 11,
    name: "ImmuneDefense Max",
    price: 73.25,
    oldPrice: 95.0,
    image: "/images/product-1.png",
    category: "Immunity",
    description: "Maximum strength immune system support",
    longDescription:
      "Maximum strength immune support supplement containing powerful antioxidants, vitamins, and minerals to strengthen the body's natural defense system and promote overall wellness.",
    ingredients: [
      { name: "Vitamin C (as Ascorbic Acid)", amount: "1000 mg" },
      { name: "Vitamin D3 (Cholecalciferol)", amount: "5000 IU" },
      { name: "Zinc (as Zinc Picolinate)", amount: "25 mg" },
      { name: "Elderberry Extract (Sambucus Nigra)", amount: "500 mg" },
      { name: "Echinacea Purpurea Extract", amount: "400 mg" },
      { name: "Astragalus Root Extract", amount: "300 mg" },
      { name: "Reishi Mushroom Extract", amount: "200 mg" },
      { name: "Quercetin", amount: "500 mg" },
    ],
    images: [
      "/images/product-1.png",
      "/images/product-1.png",
      "/images/product-1.png",
      "/images/product-1.png",
      "/images/product-1.png",
      "/images/product-1.png",
    ],
  },
  {
    id: 12,
    name: "HeartHealth Complete",
    price: 88.75,
    oldPrice: null,
    image: "/images/product-1.png",
    category: "Heart Health",
    description: "Complete cardiovascular health support",
    longDescription:
      "Comprehensive cardiovascular health supplement designed to support heart function, maintain healthy cholesterol levels, and promote optimal blood circulation.",
    ingredients: [
      { name: "CoQ10 (Ubiquinone)", amount: "200 mg" },
      { name: "Omega-3 Fish Oil", amount: "2000 mg" },
      { name: "Garlic Extract (Allicin)", amount: "400 mg" },
      { name: "Hawthorn Berry Extract", amount: "300 mg" },
      { name: "L-Arginine", amount: "1000 mg" },
      { name: "Magnesium (as Magnesium Citrate)", amount: "400 mg" },
      { name: "Vitamin B6 (Pyridoxine)", amount: "50 mg" },
      { name: "Folic Acid", amount: "800 mcg" },
    ],
    images: [
      "/images/product-1.png",
      "/images/product-1.png",
      "/images/product-1.png",
      "/images/product-1.png",
      "/images/product-1.png",
      "/images/product-1.png",
    ],
  },
  {
    id: 13,
    name: "BoneStrength Plus",
    price: 56.99,
    oldPrice: 78.5,
    image: "/images/product-1.png",
    category: "Bone Health",
    description: "Advanced bone health and calcium supplement",
    longDescription:
      "Comprehensive bone health supplement formulated to support bone density, strength, and overall skeletal health with optimal calcium absorption and bone-building nutrients.",
    ingredients: [
      { name: "Calcium (as Calcium Carbonate)", amount: "1000 mg" },
      { name: "Vitamin D3 (Cholecalciferol)", amount: "2000 IU" },
      { name: "Vitamin K2 (as MK-7)", amount: "100 mcg" },
      { name: "Magnesium (as Magnesium Oxide)", amount: "400 mg" },
      { name: "Boron (as Boron Citrate)", amount: "3 mg" },
      { name: "Zinc (as Zinc Gluconate)", amount: "15 mg" },
      { name: "Copper (as Copper Gluconate)", amount: "2 mg" },
      { name: "Manganese (as Manganese Sulfate)", amount: "2 mg" },
    ],
    images: [
      "/images/product-1.png",
      "/images/product-1.png",
      "/images/product-1.png",
      "/images/product-1.png",
      "/images/product-1.png",
      "/images/product-1.png",
    ],
  },
  {
    id: 14,
    name: "VisionCare Pro",
    price: 82.0,
    oldPrice: null,
    image: "/images/product-1.png",
    category: "Eye Health",
    description: "Professional eye health and vision support",
    longDescription:
      "Professional-grade eye health supplement designed to support vision clarity, protect against age-related eye issues, and maintain optimal eye function with powerful antioxidants.",
    ingredients: [
      { name: "Lutein (from Marigold Extract)", amount: "20 mg" },
      { name: "Zeaxanthin (from Marigold Extract)", amount: "4 mg" },
      { name: "Vitamin A (as Beta-Carotene)", amount: "5000 IU" },
      { name: "Vitamin C (as Ascorbic Acid)", amount: "500 mg" },
      { name: "Vitamin E (as d-alpha Tocopherol)", amount: "400 IU" },
      { name: "Zinc (as Zinc Oxide)", amount: "25 mg" },
      { name: "Selenium (as Selenium Methionine)", amount: "100 mcg" },
      { name: "Bilberry Extract (25% Anthocyanins)", amount: "200 mg" },
    ],
    images: [
      "/images/product-1.png",
      "/images/product-1.png",
      "/images/product-1.png",
      "/images/product-1.png",
      "/images/product-1.png",
      "/images/product-1.png",
    ],
  },
  {
    id: 15,
    name: "LiverDetox Cleanse",
    price: 69.99,
    oldPrice: 89.99,
    image: "/images/product-1.png",
    category: "Detox",
    description: "Natural liver detoxification and cleansing",
    longDescription:
      "Natural liver detoxification supplement formulated to support liver function, promote healthy detoxification processes, and maintain optimal liver health with gentle cleansing herbs.",
    ingredients: [
      { name: "Milk Thistle Extract (80% Silymarin)", amount: "500 mg" },
      { name: "Dandelion Root Extract", amount: "300 mg" },
      { name: "Artichoke Leaf Extract", amount: "250 mg" },
      { name: "Turmeric Extract (95% Curcuminoids)", amount: "400 mg" },
      { name: "N-Acetyl Cysteine (NAC)", amount: "600 mg" },
      { name: "Alpha Lipoic Acid", amount: "300 mg" },
      { name: "Choline (as Choline Bitartrate)", amount: "250 mg" },
      { name: "Beet Root Extract", amount: "200 mg" },
    ],
    images: [
      "/images/product-1.png",
      "/images/product-1.png",
      "/images/product-1.png",
      "/images/product-1.png",
      "/images/product-1.png",
      "/images/product-1.png",
    ],
  },
  {
    id: 16,
    name: "SkinGlow Essential",
    price: 47.5,
    oldPrice: null,
    image: "/images/product-1.png",
    category: "Beauty",
    description: "Essential nutrients for radiant skin",
    longDescription:
      "Essential beauty supplement formulated to promote radiant, healthy skin from within. Contains key nutrients that support collagen production, skin hydration, and overall skin health.",
    ingredients: [
      { name: "Collagen Peptides (Type I & III)", amount: "5 g" },
      { name: "Biotin", amount: "2500 mcg" },
      { name: "Vitamin C (as Ascorbic Acid)", amount: "500 mg" },
      { name: "Vitamin E (as d-alpha Tocopherol)", amount: "200 IU" },
      { name: "Zinc (as Zinc Picolinate)", amount: "15 mg" },
      { name: "Selenium (as Selenium Methionine)", amount: "100 mcg" },
      { name: "Hyaluronic Acid", amount: "50 mg" },
      { name: "Silica (from Bamboo Extract)", amount: "25 mg" },
    ],
    images: [
      "/images/product-1.png",
      "/images/product-1.png",
      "/images/product-1.png",
      "/images/product-1.png",
      "/images/product-1.png",
      "/images/product-1.png",
    ],
  },
  {
    id: 17,
    name: "MoodBalance Natural",
    price: 61.25,
    oldPrice: 79.99,
    image: "/images/product-1.png",
    category: "Mental Health",
    description: "Natural mood balancing and stress relief",
    longDescription:
      "Natural mood balancing supplement formulated to support emotional well-being, reduce stress, and promote mental clarity using clinically-proven adaptogenic herbs and amino acids.",
    ingredients: [
      { name: "Ashwagandha Extract (5% Withanolides)", amount: "600 mg" },
      { name: "Rhodiola Rosea Extract (3% Rosavins)", amount: "400 mg" },
      { name: "L-Theanine", amount: "200 mg" },
      { name: "5-HTP (5-Hydroxytryptophan)", amount: "100 mg" },
      { name: "St. John's Wort Extract (0.3% Hypericin)", amount: "300 mg" },
      { name: "Magnesium (as Magnesium Glycinate)", amount: "200 mg" },
      { name: "Vitamin B6 (Pyridoxine)", amount: "50 mg" },
      { name: "Folate (as 5-MTHF)", amount: "400 mcg" },
    ],
    images: [
      "/images/product-1.png",
      "/images/product-1.png",
      "/images/product-1.png",
      "/images/product-1.png",
      "/images/product-1.png",
      "/images/product-1.png",
    ],
  },
  {
    id: 18,
    name: "FitnessFuel Elite",
    price: 104.99,
    oldPrice: null,
    image: "/images/product-1.png",
    category: "Sports Nutrition",
    description: "Elite sports nutrition and performance fuel",
    longDescription:
      "Elite sports nutrition supplement designed to fuel athletic performance, support muscle recovery, and enhance endurance with premium protein, amino acids, and performance nutrients.",
    ingredients: [
      { name: "Whey Protein Isolate", amount: "25 g" },
      { name: "BCAAs (Branched Chain Amino Acids)", amount: "5 g" },
      { name: "Creatine Monohydrate", amount: "5 g" },
      { name: "L-Glutamine", amount: "3 g" },
      { name: "Beta-Alanine", amount: "3 g" },
      { name: "L-Carnitine L-Tartrate", amount: "1 g" },
      { name: "Electrolyte Complex", amount: "500 mg" },
      { name: "Vitamin D3", amount: "2000 IU" },
    ],
    images: [
      "/images/product-1.png",
      "/images/product-1.png",
      "/images/product-1.png",
      "/images/product-1.png",
      "/images/product-1.png",
      "/images/product-1.png",
    ],
  },
  {
    id: 19,
    name: "AntiAging Complex",
    price: 118.75,
    oldPrice: 145.0,
    image: "/images/product-1.png",
    category: "Anti-Aging",
    description: "Advanced anti-aging and longevity formula",
    longDescription:
      "Advanced anti-aging supplement formulated to support cellular health, promote longevity, and maintain youthful vitality with powerful antioxidants and anti-aging compounds.",
    ingredients: [
      { name: "Resveratrol (from Red Wine Extract)", amount: "500 mg" },
      { name: "CoQ10 (Ubiquinone)", amount: "200 mg" },
      { name: "Alpha Lipoic Acid", amount: "300 mg" },
      { name: "N-Acetyl Cysteine (NAC)", amount: "600 mg" },
      { name: "Pterostilbene", amount: "100 mg" },
      { name: "Fisetin", amount: "100 mg" },
      { name: "Quercetin", amount: "500 mg" },
      { name: "Vitamin E (as d-alpha Tocopherol)", amount: "400 IU" },
    ],
    images: [
      "/images/product-1.png",
      "/images/product-1.png",
      "/images/product-1.png",
      "/images/product-1.png",
      "/images/product-1.png",
      "/images/product-1.png",
    ],
  },
  {
    id: 20,
    name: "DigestiveEase Plus",
    price: 43.99,
    oldPrice: null,
    image: "/images/product-1.png",
    category: "Digestive Health",
    description: "Enhanced digestive comfort and support",
    longDescription:
      "Enhanced digestive health supplement designed to promote digestive comfort, support gut health, and maintain optimal digestive function with gentle, effective ingredients.",
    ingredients: [
      { name: "Ginger Root Extract", amount: "500 mg" },
      { name: "Peppermint Oil", amount: "100 mg" },
      { name: "Fennel Seed Extract", amount: "200 mg" },
      { name: "Chamomile Extract", amount: "150 mg" },
      { name: "Papain (from Papaya)", amount: "100 mg" },
      { name: "Bromelain (from Pineapple)", amount: "100 mg" },
      { name: "L-Glutamine", amount: "500 mg" },
      { name: "Digestive Enzymes Blend", amount: "200 mg" },
    ],
    images: [
      "/images/product-1.png",
      "/images/product-1.png",
      "/images/product-1.png",
      "/images/product-1.png",
      "/images/product-1.png",
      "/images/product-1.png",
    ],
  },
  {
    id: 21,
    name: "HormoneBalance Pro",
    price: 97.5,
    oldPrice: 125.0,
    image: "/images/product-1.png",
    category: "Hormonal Health",
    description: "Professional hormonal balance support",
    longDescription:
      "Professional hormonal balance supplement designed to support endocrine function, promote hormonal equilibrium, and maintain optimal hormonal health for both men and women.",
    ingredients: [
      { name: "Maca Root Extract (4:1)", amount: "1000 mg" },
      { name: "Ashwagandha Extract (5% Withanolides)", amount: "600 mg" },
      { name: "Tribulus Terrestris Extract (45% Saponins)", amount: "500 mg" },
      { name: "Fenugreek Extract (50% Saponins)", amount: "400 mg" },
      { name: "Saw Palmetto Extract (25% Fatty Acids)", amount: "300 mg" },
      { name: "Zinc (as Zinc Picolinate)", amount: "25 mg" },
      { name: "Vitamin D3 (Cholecalciferol)", amount: "2000 IU" },
      { name: "Magnesium (as Magnesium Glycinate)", amount: "200 mg" },
    ],
    images: [
      "/images/product-1.png",
      "/images/product-1.png",
      "/images/product-1.png",
      "/images/product-1.png",
      "/images/product-1.png",
      "/images/product-1.png",
    ],
  },
  {
    id: 22,
    name: "MetabolismBoost",
    price: 71.25,
    oldPrice: null,
    image: "/images/product-1.png",
    category: "Metabolism",
    description: "Natural metabolism boosting supplement",
    longDescription:
      "Natural metabolism boosting supplement formulated to enhance metabolic rate, support energy production, and promote healthy weight management with thermogenic ingredients.",
    ingredients: [
      { name: "Green Tea Extract (50% EGCG)", amount: "500 mg" },
      { name: "Cayenne Pepper Extract", amount: "100 mg" },
      { name: "Ginger Root Extract", amount: "300 mg" },
      { name: "Cinnamon Extract (4% Cinnamaldehyde)", amount: "200 mg" },
      { name: "L-Carnitine L-Tartrate", amount: "1000 mg" },
      { name: "Chromium (as Chromium Picolinate)", amount: "200 mcg" },
      { name: "B-Vitamin Complex", amount: "Various" },
      { name: "CoQ10 (Ubiquinone)", amount: "100 mg" },
    ],
    images: [
      "/images/product-1.png",
      "/images/product-1.png",
      "/images/product-1.png",
      "/images/product-1.png",
      "/images/product-1.png",
      "/images/product-1.png",
    ],
  },
  {
    id: 23,
    name: "StressRelief Natural",
    price: 54.99,
    oldPrice: 72.5,
    image: "/images/product-1.png",
    category: "Stress Relief",
    description: "Natural stress relief and relaxation aid",
    longDescription:
      "Natural stress relief supplement formulated to promote relaxation, reduce stress, and support emotional well-being using calming herbs and adaptogenic compounds.",
    ingredients: [
      { name: "Ashwagandha Extract (5% Withanolides)", amount: "600 mg" },
      { name: "L-Theanine", amount: "200 mg" },
      { name: "Chamomile Extract", amount: "300 mg" },
      { name: "Lemon Balm Extract", amount: "200 mg" },
      { name: "Passionflower Extract", amount: "150 mg" },
      { name: "Valerian Root Extract", amount: "100 mg" },
      { name: "Magnesium (as Magnesium Glycinate)", amount: "200 mg" },
      { name: "Vitamin B6 (Pyridoxine)", amount: "50 mg" },
    ],
    images: [
      "/images/product-1.png",
      "/images/product-1.png",
      "/images/product-1.png",
      "/images/product-1.png",
      "/images/product-1.png",
      "/images/product-1.png",
    ],
  },
  {
    id: 24,
    name: "MemoryEnhance Max",
    price: 108.75,
    oldPrice: null,
    image: "/images/product-1.png",
    category: "Cognitive",
    description: "Maximum memory enhancement and brain support",
    longDescription:
      "Maximum memory enhancement supplement designed to boost cognitive function, improve memory retention, and support overall brain health with advanced nootropic compounds.",
    ingredients: [
      { name: "Bacopa Monnieri Extract (50% Bacosides)", amount: "500 mg" },
      { name: "Ginkgo Biloba Extract (24% Flavonoids)", amount: "400 mg" },
      { name: "Phosphatidylserine", amount: "200 mg" },
      { name: "Acetyl-L-Carnitine", amount: "1000 mg" },
      { name: "Alpha-GPC (Alpha-Glycerylphosphorylcholine)", amount: "500 mg" },
      { name: "Vinpocetine", amount: "30 mg" },
      { name: "Huperzine A", amount: "200 mcg" },
      { name: "DHA (Docosahexaenoic Acid)", amount: "1000 mg" },
    ],
    images: [
      "/images/product-1.png",
      "/images/product-1.png",
      "/images/product-1.png",
      "/images/product-1.png",
      "/images/product-1.png",
      "/images/product-1.png",
    ],
  },
  {
    id: 25,
    name: "DetoxComplete Cleanse",
    price: 76.5,
    oldPrice: 98.99,
    image: "/images/product-1.png",
    category: "Detox",
    description: "Complete body detoxification and cleansing",
    longDescription:
      "Complete body detoxification supplement designed to support natural detoxification processes, cleanse the body, and promote overall wellness with gentle cleansing ingredients.",
    ingredients: [
      { name: "Milk Thistle Extract (80% Silymarin)", amount: "750 mg" },
      { name: "Dandelion Root Extract", amount: "500 mg" },
      { name: "Burdock Root Extract", amount: "300 mg" },
      { name: "Artichoke Leaf Extract", amount: "400 mg" },
      { name: "N-Acetyl Cysteine (NAC)", amount: "800 mg" },
      { name: "Alpha Lipoic Acid", amount: "400 mg" },
      { name: "Chlorella (Broken Cell Wall)", amount: "1000 mg" },
      { name: "Spirulina", amount: "500 mg" },
    ],
    images: [
      "/images/product-1.png",
      "/images/product-1.png",
      "/images/product-1.png",
      "/images/product-1.png",
      "/images/product-1.png",
      "/images/product-1.png",
    ],
  },
  {
    id: 26,
    name: "BeautyGlow Premium",
    price: 134.99,
    oldPrice: null,
    image: "/images/product-1.png",
    category: "Beauty",
    description: "Premium beauty and anti-aging formula",
    longDescription:
      "Premium beauty and anti-aging supplement formulated to promote radiant skin, healthy hair, and youthful appearance with luxury ingredients and advanced formulations.",
    ingredients: [
      { name: "Marine Collagen Peptides (Type I & III)", amount: "10 g" },
      { name: "Hyaluronic Acid", amount: "200 mg" },
      { name: "Biotin", amount: "10000 mcg" },
      { name: "Vitamin C (as Ascorbic Acid)", amount: "1000 mg" },
      { name: "Vitamin E (as d-alpha Tocopherol)", amount: "400 IU" },
      { name: "CoQ10 (Ubiquinone)", amount: "100 mg" },
      { name: "Resveratrol (from Red Wine Extract)", amount: "250 mg" },
      { name: "Astaxanthin", amount: "4 mg" },
    ],
    images: [
      "/images/product-1.png",
      "/images/product-1.png",
      "/images/product-1.png",
      "/images/product-1.png",
      "/images/product-1.png",
      "/images/product-1.png",
    ],
  },
  {
    id: 27,
    name: "WellnessCore Complete",
    price: 89.75,
    oldPrice: 115.0,
    image: "/images/product-1.png",
    category: "Overall Wellness",
    description: "Complete wellness and vitality support",
    longDescription:
      "Complete wellness supplement designed to support overall health, boost vitality, and promote balanced nutrition with comprehensive vitamin, mineral, and antioxidant support.",
    ingredients: [
      { name: "Multivitamin Complex", amount: "Various" },
      { name: "Omega-3 Fish Oil", amount: "1000 mg" },
      { name: "Probiotic Blend (10 strains)", amount: "15 billion CFU" },
      { name: "Antioxidant Complex", amount: "500 mg" },
      { name: "Adaptogenic Herbs Blend", amount: "400 mg" },
      { name: "Digestive Enzymes", amount: "200 mg" },
      { name: "Fiber Blend", amount: "5 g" },
      { name: "Electrolyte Complex", amount: "Various" },
    ],
    images: [
      "/images/product-1.png",
      "/images/product-1.png",
      "/images/product-1.png",
      "/images/product-1.png",
      "/images/product-1.png",
      "/images/product-1.png",
    ],
  },
  {
    id: 28,
    name: "PerformancePeak Elite",
    price: 156.25,
    oldPrice: null,
    image: "/images/product-1.png",
    category: "Performance",
    description: "Elite performance and peak physical condition",
    longDescription:
      "Elite performance supplement designed to maximize athletic potential, enhance physical performance, and support peak physical condition with premium performance-enhancing ingredients.",
    ingredients: [
      { name: "Whey Protein Isolate", amount: "30 g" },
      { name: "BCAAs (Branched Chain Amino Acids)", amount: "8 g" },
      { name: "Creatine Monohydrate", amount: "8 g" },
      { name: "L-Glutamine", amount: "5 g" },
      { name: "Beta-Alanine", amount: "5 g" },
      { name: "L-Carnitine L-Tartrate", amount: "2 g" },
      { name: "Nitric Oxide Complex", amount: "1000 mg" },
      { name: "Electrolyte & Hydration Complex", amount: "Various" },
    ],
    images: [
      "/images/product-1.png",
      "/images/product-1.png",
      "/images/product-1.png",
      "/images/product-1.png",
      "/images/product-1.png",
      "/images/product-1.png",
    ],
  },
  {
    id: 29,
    name: "HealthGuard Plus",
    price: 92.99,
    oldPrice: 118.5,
    image: "/images/product-1.png",
    category: "Immunity",
    description: "Plus immunity and health protection",
    longDescription:
      "Plus immunity supplement designed to provide maximum immune system support, protect against environmental threats, and promote long-term health with advanced immune-boosting compounds.",
    ingredients: [
      { name: "Vitamin C (as Ascorbic Acid)", amount: "1500 mg" },
      { name: "Vitamin D3 (Cholecalciferol)", amount: "5000 IU" },
      { name: "Zinc (as Zinc Picolinate)", amount: "30 mg" },
      { name: "Elderberry Extract (Sambucus Nigra)", amount: "750 mg" },
      { name: "Echinacea Purpurea Extract", amount: "600 mg" },
      { name: "Astragalus Root Extract", amount: "500 mg" },
      { name: "Reishi Mushroom Extract", amount: "300 mg" },
      { name: "Quercetin", amount: "750 mg" },
    ],
    images: [
      "/images/product-1.png",
      "/images/product-1.png",
      "/images/product-1.png",
      "/images/product-1.png",
      "/images/product-1.png",
      "/images/product-1.png",
    ],
  },
];
